### ISSUE TITLE
need option for visit frequency limit

### ISSUE THREAD

**Issue by groundwired** [groundwired/salesforce-food-bank#31]
a custom setting, if provided, will cause an alert that the person is not allowed if the last visit is within the specified number of days

also need to be able to say "once per calendar week"  "once every other calendar week" or "once per calendar month"

may need to specify first day of week?  or can we assume Sun or Mon?

**Comment by greenstork** [comment]
* Need a setting that accepts the following values - Weekly, Biweekly, Monthly, Twice Monthly, Every XX Days where you specify the exact number of days between visits (replace XX with a number).

**Comment by groundwired** [comment]
awesome work
