### ISSUE TITLE
proof of address feature

### ISSUE THREAD

**Issue by groundwired** [groundwired/salesforce-food-bank#5]
As a food bank admin, I must report to the state for funding purposes that I have verified client addresses. Once each year, a client should provide proof of address, and I need to record the proof. We still serve them if they don't have proof, but we must ask every time until we have it.

An alert appears on any household that has not verified address in the past year. Clicking the alert allows you to enter verification (a text box, any entry is accepted) and has buttons for Verify Address and Cancel. Verifying saves the text and a new date one year out.

**Comment by greenstork** [comment]
@groundwired this appears to be ready with the exception of hiding proof of address alerts for organizations that don't require it, correct?
